### ISSUE TITLE
Used Bike Checklist

### ISSUE THREAD

**Issue by davekiss** [davekiss/motorcycle#1]
$1200 Max Price.
###### Questions
- [ ] Why Selling?
- [ ] Maintenance history?
###### Crash Check
- [ ] brakes levers not bent
- [ ] forks not bent from driver perspective
- [ ] no scratches or dents on tank or fairings
- [ ] no dents in wheels
###### Tires
- [ ] no small tire cracks
- [ ] should have 1/8' or more tread / tread past washington's head on a quarter
- [ ] check stamped tire code 
  - **DOT913ACX3C2200** = 22nd week of 2000
  - **226** = 22nd week of 1996
###### Brakes
- [ ] check brakes/release in neutral, while on bike and while in front.
  - pads worn? enough lever resistance?
###### Clutch
- [ ] check clutch in 1st gear, bike should roll. 
- [ ] feel for the friction zone
- [ ] Clutch engagement should be fairly smooth, not abrupt
###### Gas tank
- [ ] gas cap locks, else -$150
- [ ] should have light/amber gas. fuel rust/sediment = rusty tank = -$150
###### Basic controls
- [ ] high/low beam works
- [ ] turn signals function/cancel
- [ ] neutral indicator light works
- [ ] starter works
- [ ] brake levers light up the brake light. 
- [ ] horn works.
- [ ] throttle should snapback.
###### Seat
- [ ] no tears, else $-100
###### Suspension
- [ ] bounce the front/rear suspension. They should go down and come back up with some resistance. should not make much noise.
###### Drivetrain
- [ ] pull chain from rear sprocket. should not expose half of a sprocket tooth. 
- [ ] teeth are not hooked in front or rear.
###### Exhaust
- [ ] no rust holes, otherwise needs replaced.
###### Fluids
- [ ] check oil level on right side of engine. Make sure the level is between the upper and lower edges of the glass (or marks on the stick) when the engine has been off for at least a few minutes and the bike is on level ground. 
  - Way too low or too high is very bad, but just outside the range probably hasn't caused any damage. oil should be honey-colored to black, not grey or white, no flecks. otherwise run.
- [ ] check coolant while engine is cold only. should be btwn high/low and neon green. brown/clear/pink/none = run.
###### Running
- [ ] speedo and odo turns from spinning front wheel
- [ ] pre-warmed engine is masking problems. clacking/shaking coffee can marbles? run.
- [ ] oil pressure light comes on when you turn on the ignition, and goes out when the engine starts! 
- [ ] twist bars. 
- [ ] shift gears.
###### Paperwork
- [ ] VIN matches title, title clean.
- [ ] Owner's manual?
